### ISSUE TITLE
track animation bug - arrow key frame jitter / loop

### ISSUE THREAD

**Issue by magland** [magland/spikesortingview#153] opened 2022-09-30 17:55 UTC

**Comment by jsoules** [comment] 2022-09-30 19:18
Eric linked https://www.figurl.org/f?v=gs://figurl/spikesortingview-9&d=sha1://7251ae9794d4dfd783fabd9b84826c86b1982f74&label=2D%20Decode%20Example&s={}

Steps to attempt to reproduce:
- click into the video
- make sure it's paused
- hit the keyboard arrow keys several times until a strange jitter loop happens

I hit the key several times a second for about a minute and didn't see any unexpected behavior. Reaching back out to the lab via Slack.

**Comment by jsoules** [comment] 2022-10-03 18:35
Updated example link:
https://www.figurl.org/f?v=gs://figurl/spikesortingview-10&d=sha1://6ca4cfd105325331086d0f5f5ab585f5c0bee529&label=Ahead%20behind%20Test-max%20bin%20spike%20count&s={}

With the playback paused, push the right arrow on the keyboard ~7 times, should see stutter. Stutter continues even after clicking to another point on the scrub bar. (Seems to go away by toggling play/pause).

Suspect race condition between the animation and the various TimeScrollView components on the right.

**Comment by jsoules** [comment] 2022-10-03 18:53
Confirmed able to reproduce effect with both the arrow keys, the arrow keys + ctrl (i.e. frame-by-frame stepping), and with clicking the on-screen buttons (which use a larger step size but are otherwise the same logic line). Interestingly, doesn't seem to happen with the mouse wheel, possibly because of the throttler (the race condition idea may be a red herring--still ruling it out).

**Comment by jsoules** [comment] 2022-10-03 19:01
Also noteworthy, this only seems to occur if the input speed exceeds the redraw speed--hitting the button 12 times in very rapid succession will likely cause it, but it won't occur if I wait a fraction of a second between keypresses for the animation to update.

**Comment by jsoules** [comment] 2022-10-04 19:44
See https://www.figurl.org/f?v=gs://figurl/franklab-views-dev1&d=sha1://6ca4cfd105325331086d0f5f5ab585f5c0bee529&label=Ahead%20behind%20Test-max%20bin%20spike%20count&s={} to review fix.

I attempted to simplify the syncing logic, with some progress, but it would need a good bit more debugging and development and wasn't showing any obvious performance improvements. I'm going to table that for now and open up a separate issue for it.

**Comment by jsoules** [comment] 2022-11-11 16:08
Resolved by figurl-franklab-views PR #3.

**Closed by jsoules** 2022-11-11 16:08 UTC
Labels: high priority
