### ISSUE TITLE
playback speed inaccurate

### ISSUE THREAD

**Issue by magland** [magland/spikesortingview#57] opened 2022-05-24 15:13 UTC
@jsoules It appears that the playback speed does not match real clock speed. Seems like 0.5x speed is the closest to real clock time, but not exactly right. I haven't looked at the details of your implementation, but I can imagine this would be tricky to get right. Maybe we should take a look together and you can explain to me how the animation frames work.

**Comment by jsoules** [comment] 2022-05-24 15:39
That's correct--in the underlying data, the difference between adjacent timestamps in the data set provided is ~0.03362 seconds; at 60 fps, this will result in a little over 2x wall-clock-speed playback.

I understood this was intentional & that FrankLab wanted to display data at a higher-than-real-time rate.

It would be possible to compute a "real-time playback" rate from the difference in timestamps and set that as an option (I actually left in some infrastructure for that in the framerate dropdown--there's the ability to pass custom framerates into the `AnimationStateControlButtons` dropdown, and the `initialReplayRate` field from the `TrackAnimationStaticData` type in `TrackPositionAnimationTypes` is meant to accommodate exactly this, even though it's not fully implemented yet--but I think we should check in with the lab/the users to see if the demand is there.

**Comment by magland** [comment] 2022-05-24 15:58
It might make sense to set `1x` to be actual real-time, but to set the default to something more convenient (maybe 2.5x).

Let's see if Frank lab folks want to chime in here. @edeno @lfrank @khl02007

**Comment by edeno** [comment] 2022-05-24 16:03
I think it makes sense for `1x` to be real-time because generally that is what you expect when you see `1x`. For decoding we will often want to see the video at much slower than real time `8x`, but if we were just trying to get a sense of the animal's behavior, playing it at faster than real-time makes much more sense.

**Comment by magland** [comment] 2022-05-24 16:09
> I think it makes sense for `1x` to be real-time because generally that is what you expect when you see `1x`. For decoding we will often want to see the video at much slower than real time `8x`, but if we were just trying to get a sense of the animal's behavior, playing it at faster than real-time makes much more sense.

Makes sense. And I guess 8x slowdown would be `0.125x`, so we'll want to make sure that's one of the options in the dropdown.

**Comment by jsoules** [comment] 2022-05-24 19:21
Adding 0.125x is no problem.

Regarding the feature request here, would the goal be to provide an additional timing setting based on the frame rate (e.g. 0.49 or whatever constitutes replaying the recorded time codes at correct intervals) or setting the base of the overall replay rate to be real-time?

Concretely, in the current sample data, there's about 34 ms per frame. Do we want:
- **Option A:** we still have 1x, 2x, 5x, ... replay rates (where 1x plays the underlying frames at 60 Hz), but with the addition of a "0.495x" real-time option; or
- **Option B:** Reset 1x speed to mean 29.75 fps, then 2x will run at 59.49 fps, 0.5x runs at 14.87 fps... etc.

I expect that what you are asking for is option B, but I am concerned this will result in noticeably choppier animation across a wider band of times than if we stick to framerates that divide more nicely with 60 Hz. (You can already see the choppiness a little bit if you slow down enough with the current timings.)

**Comment by magland** [comment] 2022-05-24 19:36
I think the data itself should come with a fps (corresponding to how the data were sampled). Then 1x means to play it at that specified fps.

**Comment by jsoules** [comment] 2022-05-24 19:55
Sorry, just to elaborate on the issue above:

The call that prompts a refresh is `requestAnimationFrame()`. This has a lot of optimizations and the browser understands what it's for, so it's really what we want to be using, but it's going to be executing its callback once per 60-Hz tick (so roughly every 16.6-bar ms, although I think it might actually be tied to the monitor's refresh rate if you're on one of these high-Hz monitors). Of course, you might not want to animate at 60 FPS, and the browser might be late executing the callback; so what you do is figure out how much time has actually elapsed since the last frame that was drawn, and then just do a no-op if not enough time has passed yet.

The problem is that clock won't go finer than 16.6 ms. In the current dataset, the 1:1 framerate would be 29.75 fps or about 33.6 ms per frame. So if we start at frame 0 and tick 0:
|frame | tick | elapsed time | next frame ideal time | effective frame rate since last frame|
|-------- | -----| ------------------|---------------------------- |------------------------------------------------|
| 0      | 0      |  0 ms            | 33.6 ms |  n/a |
| 0     |  1     | 16.6 ms         | 33.6 ms |   n/a  |
| 0     | 2      |  33.2 ms        | 33.6 ms |   n/a | 
| 1     | 3     |   49.8 ms        |  67.2 ms | 20 fps |
| 1     | 4     |   66.4 ms      |    67.2 ms | 20 fps |
| 2     | 5     |  83 ms          |    100.8 ms| 30 fps |
| 2     | 6     | 99.6 ms        |    100.8 ms | 30 fps |
| 3     | 7      |  116.2 ms   |   134.45 ms | 30 fps |
| 3     |   8   |  132.8 ms |     134.45 ms |  30 fps |
| 4     | 9    |  149.4 ms |   168.07 ms | 30 fps |
| 5    |  10 |   166.0 ms |  168.07 ms | 30 fps |

...you get the idea. A couple more steps and we'll catch up and have another pair of frames that are effectively 20 fps apart, then drop back down to 30 fps again. I think the effect winds up only getting more noticeable when you go at slower speeds--like 1/8x, which if the 1:1 framerate is 29.75, would be 268.9 ms per frame, so you see jumps in the effective framerate basically one frame out of 16.

I'll code it up, though, so we can see what it looks like in practice.

**Comment by jsoules** [comment] 2022-05-26 16:39
Addressed by PR #58.

**Closed by jsoules** 2022-05-26 16:39 UTC
